chore(deps): update devdependencies (#39)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@edge-runtime/jest-environment](https://edge-runtime.vercel.app/packages/jest-environment)
([source](https://togithub.com/vercel/edge-runtime/tree/HEAD/packages/jest-environment))
| [`2.3.7` ->
`2.3.8`](https://renovatebot.com/diffs/npm/@edge-runtime%2fjest-environment/2.3.7/2.3.8)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@edge-runtime%2fjest-environment/2.3.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@edge-runtime%2fjest-environment/2.3.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@edge-runtime%2fjest-environment/2.3.7/2.3.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@edge-runtime%2fjest-environment/2.3.7/2.3.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [@edge-runtime/types](https://edge-runtime.vercel.app/packages/types)
([source](https://togithub.com/vercel/edge-runtime/tree/HEAD/packages/types))
| [`2.2.7` ->
`2.2.8`](https://renovatebot.com/diffs/npm/@edge-runtime%2ftypes/2.2.7/2.2.8)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@edge-runtime%2ftypes/2.2.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@edge-runtime%2ftypes/2.2.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@edge-runtime%2ftypes/2.2.7/2.2.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@edge-runtime%2ftypes/2.2.7/2.2.8?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/jest](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/jest)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/jest))
| [`29.5.11` ->
`29.5.12`](https://renovatebot.com/diffs/npm/@types%2fjest/29.5.11/29.5.12)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fjest/29.5.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fjest/29.5.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fjest/29.5.11/29.5.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fjest/29.5.11/29.5.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/node](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://togithub.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node))
| [`20.11.0` ->
`20.11.16`](https://renovatebot.com/diffs/npm/@types%2fnode/20.11.0/20.11.16)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/20.11.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/20.11.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/20.11.0/20.11.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/20.11.0/20.11.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [@vercel/style-guide](https://togithub.com/vercel/style-guide) |
[`5.1.0` ->
`5.2.0`](https://renovatebot.com/diffs/npm/@vercel%2fstyle-guide/5.1.0/5.2.0)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@vercel%2fstyle-guide/5.2.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@vercel%2fstyle-guide/5.2.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@vercel%2fstyle-guide/5.1.0/5.2.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@vercel%2fstyle-guide/5.1.0/5.2.0?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [husky](https://togithub.com/typicode/husky) | [`9.0.6` ->
`9.0.10`](https://renovatebot.com/diffs/npm/husky/9.0.6/9.0.10) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/husky/9.0.10?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/husky/9.0.10?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/husky/9.0.6/9.0.10?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/husky/9.0.6/9.0.10?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [lint-staged](https://togithub.com/okonet/lint-staged) | [`15.2.0` ->
`15.2.1`](https://renovatebot.com/diffs/npm/lint-staged/15.2.0/15.2.1) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/lint-staged/15.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lint-staged/15.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lint-staged/15.2.0/15.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lint-staged/15.2.0/15.2.1?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [prettier](https://prettier.io)
([source](https://togithub.com/prettier/prettier)) | [`3.2.2` ->
`3.2.5`](https://renovatebot.com/diffs/npm/prettier/3.2.2/3.2.5) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/prettier/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/prettier/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/prettier/3.2.2/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/prettier/3.2.2/3.2.5?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [ts-jest](https://kulshekhar.github.io/ts-jest)
([source](https://togithub.com/kulshekhar/ts-jest)) | [`29.1.1` ->
`29.1.2`](https://renovatebot.com/diffs/npm/ts-jest/29.1.1/29.1.2) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/ts-jest/29.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/ts-jest/29.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/ts-jest/29.1.1/29.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/ts-jest/29.1.1/29.1.2?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>vercel/edge-runtime
(@&#8203;edge-runtime/jest-environment)</summary>

###
[`v2.3.8`](https://togithub.com/vercel/edge-runtime/blob/HEAD/packages/jest-environment/CHANGELOG.md#238)

[Compare
Source](https://togithub.com/vercel/edge-runtime/compare/@edge-runtime/jest-environment@2.3.7...@edge-runtime/jest-environment@2.3.8)

##### Patch Changes

- Updated dependencies
\[[`c313a3cbde5b06ee4ff716a25fbd0118cdfb571b`](https://togithub.com/vercel/edge-runtime/commit/c313a3cbde5b06ee4ff716a25fbd0118cdfb571b)]:
-
[@&#8203;edge-runtime/vm](https://togithub.com/edge-runtime/vm)[@&#8203;3](https://togithub.com/3).1.8

</details>

<details>
<summary>vercel/edge-runtime (@&#8203;edge-runtime/types)</summary>

###
[`v2.2.8`](https://togithub.com/vercel/edge-runtime/blob/HEAD/packages/types/CHANGELOG.md#228)

[Compare
Source](https://togithub.com/vercel/edge-runtime/compare/@edge-runtime/types@2.2.7...@edge-runtime/types@2.2.8)

##### Patch Changes

- Updated dependencies
\[[`d26e2ddaffdf7f9ae9bbcdeae00175dabd4a7e44`](https://togithub.com/vercel/edge-runtime/commit/d26e2ddaffdf7f9ae9bbcdeae00175dabd4a7e44),
[`c313a3cbde5b06ee4ff716a25fbd0118cdfb571b`](https://togithub.com/vercel/edge-runtime/commit/c313a3cbde5b06ee4ff716a25fbd0118cdfb571b)]:
-
[@&#8203;edge-runtime/primitives](https://togithub.com/edge-runtime/primitives)[@&#8203;4](https://togithub.com/4).0.6

</details>

<details>
<summary>vercel/style-guide (@&#8203;vercel/style-guide)</summary>

###
[`v5.2.0`](https://togithub.com/vercel/style-guide/releases/tag/v5.2.0)

[Compare
Source](https://togithub.com/vercel/style-guide/compare/v5.1.0...v5.2.0)

##### Bug Fixes

- **typescript:** `es2023` is not valid
([#&#8203;84](https://togithub.com/vercel/style-guide/issues/84))
([3d9dbdc](https://togithub.com/vercel/style-guide/commit/3d9dbdc4b458e3fb34b99a7f02ce237870daba90))

##### Features

- **typescript:** add multiple tsconfigs
([#&#8203;60](https://togithub.com/vercel/style-guide/issues/60))
([3991e02](https://togithub.com/vercel/style-guide/commit/3991e02ab36fd0175148165c6a0f2c69a878db5d))

</details>

<details>
<summary>typicode/husky (husky)</summary>

###
[`v9.0.10`](https://togithub.com/typicode/husky/releases/tag/v9.0.10)

[Compare
Source](https://togithub.com/typicode/husky/compare/v9.0.9...v9.0.10)

- fix: rename index.d.ts to index.d.mts by
[@&#8203;mrkjdy](https://togithub.com/mrkjdy) in
[https://github.com/typicode/husky/pull/1379](https://togithub.com/typicode/husky/pull/1379)

### [`v9.0.9`](https://togithub.com/typicode/husky/releases/tag/v9.0.9)

[Compare
Source](https://togithub.com/typicode/husky/compare/v9.0.8...v9.0.9)

- refactor: rename files by
[@&#8203;typicode](https://togithub.com/typicode) in
[https://github.com/typicode/husky/pull/1378](https://togithub.com/typicode/husky/pull/1378)

### [`v9.0.8`](https://togithub.com/typicode/husky/releases/tag/v9.0.8)

[Compare
Source](https://togithub.com/typicode/husky/compare/v9.0.7...v9.0.8)

- docs: update index.md by
[@&#8203;khaledYS](https://togithub.com/khaledYS) in
[https://github.com/typicode/husky/pull/1369](https://togithub.com/typicode/husky/pull/1369)
- Fix tab detection on install command by
[@&#8203;glensc](https://togithub.com/glensc) in
[https://github.com/typicode/husky/pull/1376](https://togithub.com/typicode/husky/pull/1376)
- refactor: reduce file size by
[@&#8203;typicode](https://togithub.com/typicode) in
[https://github.com/typicode/husky/pull/1377](https://togithub.com/typicode/husky/pull/1377)

### [`v9.0.7`](https://togithub.com/typicode/husky/releases/tag/v9.0.7)

[Compare
Source](https://togithub.com/typicode/husky/compare/v9.0.6...v9.0.7)

-   fix: typo and source `~/.huskyrc` correctly (compatibility with v8)
- docs: fix example by [@&#8203;typicode](https://togithub.com/typicode)
in
[https://github.com/typicode/husky/pull/1363](https://togithub.com/typicode/husky/pull/1363)

</details>

<details>
<summary>okonet/lint-staged (lint-staged)</summary>

###
[`v15.2.1`](https://togithub.com/okonet/lint-staged/blob/HEAD/CHANGELOG.md#1521)

[Compare
Source](https://togithub.com/okonet/lint-staged/compare/v15.2.0...v15.2.1)

##### Patch Changes

- [#&#8203;1387](https://togithub.com/lint-staged/lint-staged/pull/1387)
[`e4023f6`](https://togithub.com/lint-staged/lint-staged/commit/e4023f687616dcf4816545b8eefbcce50e255c9c)
Thanks [@&#8203;iiroj](https://togithub.com/iiroj)! - Ignore stdin of
spawned commands so that they don't get stuck waiting. Until now,
*lint-staged* has used the default settings to spawn linter commands.
This means the `stdin` of the spawned commands has accepted input, and
essentially gotten stuck waiting. Now the `stdin` is ignored and
commands will no longer get stuck. If you relied on this behavior,
please open a new issue and describe how; the behavior has not been
intended.

</details>

<details>
<summary>prettier/prettier (prettier)</summary>

###
[`v3.2.5`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#325)

[Compare
Source](https://togithub.com/prettier/prettier/compare/3.2.4...3.2.5)

[diff](https://togithub.com/prettier/prettier/compare/3.2.4...3.2.5)

##### Support Angular inline styles as single template literal
([#&#8203;15968](https://togithub.com/prettier/prettier/pull/15968) by
[@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

[Angular
v17](https://blog.angular.io/introducing-angular-v17-4d7033312e4b)
supports single string inline styles.

<!-- prettier-ignore -->

```ts
// Input
@&#8203;Component({
  template: `<div>...</div>`,
  styles: `h1 { color: blue; }`,
})
export class AppComponent {}

// Prettier 3.2.4
@&#8203;Component({
  template: `<div>...</div>`,
  styles: `h1 { color: blue; }`,
})
export class AppComponent {}

// Prettier 3.2.5
@&#8203;Component({
  template: `<div>...</div>`,
  styles: `
    h1 {
      color: blue;
    }
  `,
})
export class AppComponent {}

```

##### Unexpected embedded formatting for Angular template
([#&#8203;15969](https://togithub.com/prettier/prettier/pull/15969) by
[@&#8203;JounQin](https://togithub.com/JounQin))

Computed template should not be considered as Angular component template

<!-- prettier-ignore -->

```ts
// Input
const template = "foobar";

@&#8203;Component({
  [template]: `<h1>{{       hello }}</h1>`,
})
export class AppComponent {}

// Prettier 3.2.4
const template = "foobar";

@&#8203;Component({
  [template]: `<h1>{{ hello }}</h1>`,
})
export class AppComponent {}

// Prettier 3.2.5
const template = "foobar";

@&#8203;Component({
  [template]: `<h1>{{       hello }}</h1>`,
})
export class AppComponent {}
```

##### Use `"json"` parser for `tsconfig.json` by default
([#&#8203;16012](https://togithub.com/prettier/prettier/pull/16012) by
[@&#8203;sosukesuzuki](https://togithub.com/sosukesuzuki))

In
[v2.3.0](https://prettier.io/blog/2024/01/12/3.2.0#new-jsonc-parser-added-15831httpsgithubcomprettierprettierpull15831-by-fiskerhttpsgithubcomfisker),
we introduced `"jsonc"` parser which adds trialing comma **by default**.

When adding a new parser we also define how it will be used based on the
[`linguist-languages`](https://www.npmjs.com/package/linguist-languages)
data.

`tsconfig.json` is a special file used by
[TypeScript](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#using-tsconfigjson-or-jsconfigjson),
it uses `.json` file extension, but it actually uses the [JSON with
Comments](https://code.visualstudio.com/docs/languages/json#\_json-with-comments)
syntax. However, we found that there are many third-party tools not
recognize it correctly because of the confusing `.json` file extension.

We decide to treat it as a JSON file for now to avoid the extra
configuration step.

To keep using the `"jsonc"` parser for your `tsconfig.json` files, add
the following to your `.pretterrc` file

```json
{
  "overrides": [
    {
      "files": ["tsconfig.json", "jsconfig.json"],
      "options": {
        "parser": "jsonc"
      }
    }
  ]
}
```

<!-- prettier-ignore -->

```
```

###
[`v3.2.4`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#324)

[Compare
Source](https://togithub.com/prettier/prettier/compare/3.2.3...3.2.4)

[diff](https://togithub.com/prettier/prettier/compare/3.2.3...3.2.4)

##### Fix incorrect parser inference
([#&#8203;15947](https://togithub.com/prettier/prettier/pull/15947) by
[@&#8203;fisker](https://togithub.com/fisker))

Files like `.eslintrc.json` were incorrectly formatted as JSONC files.

<!-- prettier-ignore -->

```jsx
// Input
prettier --file-info .eslintrc.json
{ "ignored": false, "inferredParser": "jsonc" }

// Prettier 3.2.4
prettier --file-info .eslintrc.json
{ "ignored": false, "inferredParser": "json" }
```

###
[`v3.2.3`](https://togithub.com/prettier/prettier/blob/HEAD/CHANGELOG.md#323)

[Compare
Source](https://togithub.com/prettier/prettier/compare/3.2.2...3.2.3)

[diff](https://togithub.com/prettier/prettier/compare/3.2.2...3.2.3)

##### Throw errors for invalid code
([#&#8203;15881](https://togithub.com/prettier/prettier/pull/15881) by
[@&#8203;fisker](https://togithub.com/fisker),
[@&#8203;Josh-Cena](https://togithub.com/Josh-Cena),
[@&#8203;auvred](https://togithub.com/auvred))

<!-- prettier-ignore -->

```ts
// Input
1++;

// Prettier 3.2.2
1++;

// Prettier 3.2.3
SyntaxError: Invalid left-hand side expression in unary operation (1:1)
> 1 | 1++;
    | ^
```

<!-- prettier-ignore -->

```ts
// Input
try {} catch (error = 1){}

// Prettier 3.2.2
try {
} catch (error) {}

// Prettier 3.2.3
SyntaxError: Catch clause variable cannot have an initializer. (1:23)
> 1 | try {} catch (error = 1){}
    |                       ^
```

##### Fix parser inference
([#&#8203;15927](https://togithub.com/prettier/prettier/pull/15927) by
[@&#8203;fisker](https://togithub.com/fisker))

<!-- prettier-ignore -->

```console
// Prettier 3.2.2
prettier --file-info tsconfig.json
{ "ignored": false, "inferredParser": "json" }

// Prettier 3.2.3
prettier --file-info tsconfig.json
{ "ignored": false, "inferredParser": "jsonc" }
```

</details>

<details>
<summary>kulshekhar/ts-jest (ts-jest)</summary>

###
[`v29.1.2`](https://togithub.com/kulshekhar/ts-jest/blob/HEAD/CHANGELOG.md#2912-2024-01-22)

[Compare
Source](https://togithub.com/kulshekhar/ts-jest/compare/v29.1.1...v29.1.2)

##### Bug Fixes

- calculated cache key based on `supportsStaticESM`
([a5d6f2d](https://togithub.com/kulshekhar/ts-jest/commit/a5d6f2d4f4bfa1c7c217f6faf9310958797b436f))
- correct error handling in `processAsync`
([e7be4bf](https://togithub.com/kulshekhar/ts-jest/commit/e7be4bf6a863cd76efec28f40fdd5193b2f50bad)),
closes
[#&#8203;4207](https://togithub.com/kulshekhar/ts-jest/issues/4207)
- use `Config.ProjectConfig`
([918312b](https://togithub.com/kulshekhar/ts-jest/commit/918312bee22a795ec6bb347f95df4c1ff0a054de)),
closes
[#&#8203;4028](https://togithub.com/kulshekhar/ts-jest/issues/4028)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - "before 4am on Monday" (UTC).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config help](https://togithub.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/tnez/starter-npm-pkg).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNy4xMjcuMCIsInVwZGF0ZWRJblZlciI6IjM3LjE1My4yIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>