chore(deps): update devdependencies (#90)
This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
|
[@changesets/cli](https://redirect.github.com/changesets/changesets/tree/main#readme)
([source](https://redirect.github.com/changesets/changesets)) |
[`2.27.11` ->
`2.27.12`](https://renovatebot.com/diffs/npm/@changesets%2fcli/2.27.11/2.27.12)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@changesets%2fcli/2.27.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@changesets%2fcli/2.27.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@changesets%2fcli/2.27.11/2.27.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@changesets%2fcli/2.27.11/2.27.12?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
|
[@types/node](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node)
([source](https://redirect.github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node))
| [`20.17.14` ->
`20.17.16`](https://renovatebot.com/diffs/npm/@types%2fnode/20.17.14/20.17.16)
|
[![age](https://developer.mend.io/api/mc/badges/age/npm/@types%2fnode/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/@types%2fnode/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/@types%2fnode/20.17.14/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/@types%2fnode/20.17.14/20.17.16?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [lint-staged](https://redirect.github.com/lint-staged/lint-staged) |
[`15.4.1` ->
`15.4.3`](https://renovatebot.com/diffs/npm/lint-staged/15.4.1/15.4.3) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/lint-staged/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/lint-staged/15.4.1/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/lint-staged/15.4.1/15.4.3?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
| [tsup](https://tsup.egoist.dev/)
([source](https://redirect.github.com/egoist/tsup)) | [`8.3.5` ->
`8.3.6`](https://renovatebot.com/diffs/npm/tsup/8.3.5/8.3.6) |
[![age](https://developer.mend.io/api/mc/badges/age/npm/tsup/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://developer.mend.io/api/mc/badges/adoption/npm/tsup/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://developer.mend.io/api/mc/badges/compatibility/npm/tsup/8.3.5/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://developer.mend.io/api/mc/badges/confidence/npm/tsup/8.3.5/8.3.6?slim=true)](https://docs.renovatebot.com/merge-confidence/)
|

---

### Release Notes

<details>
<summary>changesets/changesets (@&#8203;changesets/cli)</summary>

###
[`v2.27.12`](https://redirect.github.com/changesets/changesets/releases/tag/%40changesets/cli%402.27.12)

[Compare
Source](https://redirect.github.com/changesets/changesets/compare/@changesets/cli@2.27.11...@changesets/cli@2.27.12)

##### Patch Changes

-
[#&#8203;1562](https://redirect.github.com/changesets/changesets/pull/1562)
[`a0f87f1`](https://redirect.github.com/changesets/changesets/commit/a0f87f1ce596e7c5c316edc24d5d4571e6acd4d7)
Thanks [@&#8203;Netail](https://redirect.github.com/Netail),
[@&#8203;cefn](https://redirect.github.com/cefn)! - Fixed changelog
application when executing using `npx` and similar tools

- Updated dependencies
\[[`a0f87f1`](https://redirect.github.com/changesets/changesets/commit/a0f87f1ce596e7c5c316edc24d5d4571e6acd4d7)]:
-
[@&#8203;changesets/apply-release-plan](https://redirect.github.com/changesets/apply-release-plan)[@&#8203;7](https://redirect.github.com/7).0.8

</details>

<details>
<summary>lint-staged/lint-staged (lint-staged)</summary>

###
[`v15.4.3`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1543)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.2...v15.4.3)

##### Patch Changes

-
[#&#8203;1512](https://redirect.github.com/lint-staged/lint-staged/pull/1512)
[`cbfed1d`](https://redirect.github.com/lint-staged/lint-staged/commit/cbfed1dfd2465c4198c692955281f0836600bea1)
Thanks [@&#8203;tarik02](https://redirect.github.com/tarik02)! - Adjust
TypeScript types for the default export so that it can be used as a
value without error TS2693.

###
[`v15.4.2`](https://redirect.github.com/lint-staged/lint-staged/blob/HEAD/CHANGELOG.md#1542)

[Compare
Source](https://redirect.github.com/lint-staged/lint-staged/compare/v15.4.1...v15.4.2)

##### Patch Changes

-
[#&#8203;1509](https://redirect.github.com/lint-staged/lint-staged/pull/1509)
[`8827ebf`](https://redirect.github.com/lint-staged/lint-staged/commit/8827ebf29dc8f25149a36450b4a0023425202e18)
Thanks [@&#8203;iiroj](https://redirect.github.com/iiroj)! - Change
*lint-staged*'s dependencies to use [caret (`^`)
ranges](https://docs.npmjs.com/cli/v6/using-npm/semver#caret-ranges-123-025-004)
instead of [tilde
(`~`)](https://docs.npmjs.com/cli/v6/using-npm/semver#tilde-ranges-123-12-1).
This makes it easier for package managers to perform dependency
management when minor-level updates are also permitted instead of just
patch-level.

</details>

<details>
<summary>egoist/tsup (tsup)</summary>

###
[`v8.3.6`](https://redirect.github.com/egoist/tsup/releases/tag/v8.3.6)

[Compare
Source](https://redirect.github.com/egoist/tsup/compare/v8.3.5...v8.3.6)

#####    🐞 Bug Fixes

- Don't await sub-process of `onSuccess`  -  by
[@&#8203;laat](https://redirect.github.com/laat) in
[https://github.com/egoist/tsup/issues/1256](https://redirect.github.com/egoist/tsup/issues/1256)
[<samp>(314a6)</samp>](https://redirect.github.com/egoist/tsup/commit/314a6d7)

#####     [View changes on
GitHub](https://redirect.github.com/egoist/tsup/compare/v8.3.5...v8.3.6)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - "before 4am on Monday" (UTC).

🚦 **Automerge**: Enabled.

♻ **Rebasing**: Whenever PR is behind base branch, or you tick the
rebase/retry checkbox.

👻 **Immortal**: This PR will be recreated if closed unmerged. Get
[config
help](https://redirect.github.com/renovatebot/renovate/discussions) if
that's undesired.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR was generated by [Mend Renovate](https://mend.io/renovate/).
View the [repository job
log](https://developer.mend.io/github/tnez/starter-npm-pkg).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS4xMjUuMSIsInVwZGF0ZWRJblZlciI6IjM5LjEyNS4xIiwidGFyZ2V0QnJhbmNoIjoibWFpbiIsImxhYmVscyI6W119-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>